ADD_DRIVER = "ADD_DRIVER"
ADD_RIDER = "ADD_RIDER"
MATCH = "MATCH"
START_RIDE = "START_RIDE"
STOP_RIDE = "STOP_RIDE"
BILL = "BILL"

VALID_COMMANDS_VS_ARGUMENTS = {ADD_DRIVER: 3, ADD_RIDER: 3, MATCH: 1, START_RIDE: 3, STOP_RIDE: 4, BILL: 1}
